change action worklow to the new one

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -8,15 +8,15 @@ jobs:
   increment_version:
     runs-on: ubuntu-latest
     env:
-      APP_NAME: backendSetting
-      NEW_VERSION: 1.5.6
-      K8S_PATH_VALUE: k8s/charts/offline-configurator/values-dev.yaml
+      APP_NAME: synergy-settings-api
+      NEW_VERSION: 3.3.3
+      K8S_PATH_VALUE: 3.0/values.yaml
     steps:
       - name: Checkout repository
         uses: actions/checkout@v3.5.2
         with:
           repository: YevhenZzz/changing-value-demo
-          ref: master
+          ref: focalpoint_3.0
           token: ${{ secrets.PAT_TOKEN }}
 
       - name: Set up Git
@@ -28,20 +28,19 @@ jobs:
 
       - name: Increment version in new branch
         run: |
-          CURRENT_VERSION=$(grep 'apiVersion:' ${{ env.K8S_PATH_VALUE }} | awk '{print $2}')
-          NEW_VERSION=${{ env.NEW_VERSION }}
-          ENVIRONMENT_NAME=$(echo ${{ env.K8S_PATH_VALUE }} | awk -F'/' '{print $NF}' | awk -F'-' '{print $2}' | awk -F'.' '{print $1}')
-          echo "ENVIRONMENT_NAME=$ENVIRONMENT_NAME" >> $GITHUB_ENV
-          
-          git checkout -b "${{ env.APP_NAME }}-$ENVIRONMENT_NAME-4"
-          sed -i "s/apiVersion: $CURRENT_VERSION/apiVersion: $NEW_VERSION/" ${{ env.K8S_PATH_VALUE }}
-          git add ${{ env.K8S_PATH_VALUE }}
-          git commit -m "Update api version on $ENVIRONMENT_NAME environment from $CURRENT_VERSION to $NEW_VERSION"
-          git push origin "${{ env.APP_NAME }}-$ENVIRONMENT_NAME-4"
-
-      - name: Create pull request
-        run: |
-          gh pr create -B master -H "${{ env.APP_NAME }}-$ENVIRONMENT_NAME-4" --title "Update api version on $ENVIRONMENT_NAME environment" --body "Created by Github action."
-        env:
-          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
+          NEW_VERSION=${{ inputs.new_version }}
+          APP_NAME=${{ inputs.app_name }}
+          YAML_FILE=${{ inputs.K8S_PATH_VALUE }}
+        
+          if grep -q "${APP_NAME}:" ${YAML_FILE}; then
+            # Update the version for the specific service
+            sed -i "/${APP_NAME}:/{N;s/version: [^ ]*/version: $NEW_VERSION/}" ${YAML_FILE}
+        
+            git add ${YAML_FILE}
+            git commit -m "Update ${APP_NAME} version to ${NEW_VERSION}"
+            git push origin focalpoint_3.0
+          else
+            echo "Error: Service ${APP_NAME} not found in ${YAML_FILE}"
+            exit 1
+          fi
 # sadas
